services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RKL\AutocompleteForIndexedSearch\:
    resource: '../Classes/*'

  # required for TYPO3 12 compatibility
  RKL\AutocompleteForIndexedSearch\ViewHelpers\AutocompletesuggestionsViewHelper:
    public: true
    shared: false
